GRANT CREATE SESSION TO DIWEN2;
GRANT CREATE TABLE TO DIWEN2;
GRANT CREATE VIEW TO DIWEN2;
GRANT CREATE SEQUENCE TO DIWEN2;
GRANT CREATE TRIGGER TO DIWEN2;
GRANT CREATE PROCEDURE TO DIWEN2;
GRANT UNLIMITED TABLESPACE TO DIWEN2;