-- ===========================================================
--  SCHEMA: ZEROCOOL
--  PROJECT: Social Threat Guardian
--  VERSION: v3
-- ===========================================================

------------------------------------------------------------
-- DROP TABLES
------------------------------------------------------------
DROP TABLE UserRoleMapping CASCADE CONSTRAINTS;
DROP TABLE UserPreferencePlatforms CASCADE CONSTRAINTS;
DROP TABLE UserPreferences CASCADE CONSTRAINTS;
DROP TABLE Bookmarks CASCADE CONSTRAINTS;
DROP TABLE Comments CASCADE CONSTRAINTS;
DROP TABLE ProcessedPosts CASCADE CONSTRAINTS;
DROP TABLE RawPosts CASCADE CONSTRAINTS;
DROP TABLE APILogs CASCADE CONSTRAINTS;
DROP TABLE EmailQueue CASCADE CONSTRAINTS;
DROP TABLE Notifications CASCADE CONSTRAINTS;
DROP TABLE PlatformSentimentIndex CASCADE CONSTRAINTS;
DROP TABLE GlobalSentimentIndex CASCADE CONSTRAINTS;
DROP TABLE Platforms CASCADE CONSTRAINTS;
DROP TABLE UserRoles CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;

------------------------------------------------------------
-- USERS
------------------------------------------------------------
CREATE TABLE Users (
    user_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR2(100) NOT NULL UNIQUE,
    email             VARCHAR2(255) NOT NULL UNIQUE,
    password_hash     VARCHAR2(255) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login        TIMESTAMP
);

------------------------------------------------------------
-- USER ROLES
------------------------------------------------------------
CREATE TABLE UserRoles (
    role_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name         VARCHAR2(50) NOT NULL UNIQUE,
    description       VARCHAR2(255)
);

------------------------------------------------------------
-- USER ROLE MAPPING
------------------------------------------------------------
CREATE TABLE UserRoleMapping (
    user_id           NUMBER NOT NULL,
    role_id           NUMBER NOT NULL,
    CONSTRAINT pk_userrolemap PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_urm_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_urm_role FOREIGN KEY (role_id) REFERENCES UserRoles(role_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- PLATFORMS
------------------------------------------------------------
CREATE TABLE Platforms (
    platform_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR2(100) NOT NULL UNIQUE,
    api_source        VARCHAR2(255)
);

------------------------------------------------------------
-- RAW POSTS
------------------------------------------------------------
CREATE TABLE RawPosts (
    post_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id       NUMBER NOT NULL,
    hashtag           VARCHAR2(255),
    username          VARCHAR2(100),
    display_name      VARCHAR2(100),
    post_content      CLOB,
    created_at        TIMESTAMP,
    language          VARCHAR2(10),
    url               VARCHAR2(500),
    visibility        CHAR(1) CHECK (visibility IN ('T','F')),
    collected_at      TIMESTAMP,
    CONSTRAINT fk_raw_platform FOREIGN KEY (platform_id)
        REFERENCES Platforms(platform_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- PROCESSED POSTS
------------------------------------------------------------
CREATE TABLE ProcessedPosts (
    processed_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_post_id          NUMBER NOT NULL,
    platform_id          NUMBER NOT NULL,
    hashtag              VARCHAR2(255),
    post_content         CLOB,
    created_at           TIMESTAMP,
    language             VARCHAR2(10),
    url                  VARCHAR2(500),
    threat_level         VARCHAR2(50),
    contains_hate_speech NUMBER(1) CHECK (contains_hate_speech IN (0,1)),
    processed_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processing_status    VARCHAR2(50) CHECK (processing_status IN ('SUCCESS','FAILED','RETRY')),
    CONSTRAINT fk_proc_raw FOREIGN KEY (raw_post_id)
        REFERENCES RawPosts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_proc_platform FOREIGN KEY (platform_id)
        REFERENCES Platforms(platform_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- COMMENTS
------------------------------------------------------------
CREATE TABLE Comments (
    comment_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER NOT NULL,
    processed_id      NUMBER NOT NULL,
    comment_text      CLOB,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP,
    is_deleted        NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0,1)),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_post FOREIGN KEY (processed_id)
        REFERENCES ProcessedPosts(processed_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- BOOKMARKS
------------------------------------------------------------
CREATE TABLE Bookmarks (
    bookmark_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER NOT NULL,
    processed_id      NUMBER NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted        NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0,1)),
    CONSTRAINT fk_bookmark_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookmark_post FOREIGN KEY (processed_id)
        REFERENCES ProcessedPosts(processed_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- USER PREFERENCES
------------------------------------------------------------
CREATE TABLE UserPreferences (
    preference_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER NOT NULL,
    language             VARCHAR2(10),
    alert_threshold      NUMBER(5,2),
    notification_method  VARCHAR2(50),
    keywords             CLOB CHECK (keywords IS JSON),
    CONSTRAINT fk_pref_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- USER PREFERENCE ↔ PLATFORM (bridge)
------------------------------------------------------------
CREATE TABLE UserPreferencePlatforms (
    preference_id   NUMBER NOT NULL,
    platform_id     NUMBER NOT NULL,
    CONSTRAINT pk_pref_platform PRIMARY KEY (preference_id, platform_id),
    CONSTRAINT fk_prefplat_pref FOREIGN KEY (preference_id)
        REFERENCES UserPreferences(preference_id) ON DELETE CASCADE,
    CONSTRAINT fk_prefplat_platform FOREIGN KEY (platform_id)
        REFERENCES Platforms(platform_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- NOTIFICATIONS
------------------------------------------------------------
CREATE TABLE Notifications (
    notification_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER NOT NULL,
    type             VARCHAR2(50) CHECK (type IN ('threshold','keyword_alert')),
    message          VARCHAR2(1000),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_status      NUMBER(1) DEFAULT 0 CHECK (read_status IN (0,1)),
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- EMAIL QUEUE
------------------------------------------------------------
CREATE TABLE EmailQueue (
    email_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    subject      VARCHAR2(255),
    body         CLOB,
    status       VARCHAR2(50) CHECK (status IN ('sent','failed','pending')),
    CONSTRAINT fk_email_user FOREIGN KEY (user_id)
        REFERENCES Users(user_id) ON DELETE CASCADE
);

------------------------------------------------------------
-- API LOGS
------------------------------------------------------------
CREATE TABLE APILogs (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint      VARCHAR2(255),
    method        VARCHAR2(20),
    response_time NUMBER,
    status_code   NUMBER,
    timestamp     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------
-- GLOBAL SENTIMENT INDEX
------------------------------------------------------------
CREATE TABLE GlobalSentimentIndex (
    global_index_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    score             FLOAT
);

------------------------------------------------------------
-- PLATFORM SENTIMENT INDEX
------------------------------------------------------------
CREATE TABLE PlatformSentimentIndex (
    index_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id      NUMBER NOT NULL,
    global_index_id  NUMBER NULL,
    timestamp        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sentiment_score  FLOAT,
    CONSTRAINT fk_plat_index_platform FOREIGN KEY (platform_id)
        REFERENCES Platforms(platform_id) ON DELETE CASCADE,
    CONSTRAINT fk_plat_index_global FOREIGN KEY (global_index_id)
        REFERENCES GlobalSentimentIndex(global_index_id) ON DELETE SET NULL
);